site_name: 'Bellairs Panangaden Workshops'
site_url: ''
repo_url: ''
site_description: ''
site_author: 'Alexandra Silva'

theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: 'true'
    #  logo: 'assets/images/favicon.ico'
    #  favicon: 'assets/images/favicon.ico'
  palette:
    primary: blue
    accent: blue

nav:
  - Home:
    - About: 'index.md'
    - 2025: 'pages/2025.md'
    - 2024: 'pages/2024.md'
    - 2023: 'pages/2023.md'
    - 2022: 'pages/2022.md'
    - 2020: 'pages/2020.md'
    - 2019: 'pages/2019.md'
    - 2018: 'pages/2018.md'
    - 2017: 'pages/2017.md'
    - 2016: 'pages/2016.md'
    - 2015: 'pages/2015.md'
    - 2014: 'pages/2014.md'
    - 2013-2003: 'pages/rest.md'
    - General Info: 'pages/general.md'
